name: Snap Build

on: 
  workflow_dispatch:
  push:

defaults:
  run:
    shell: bash

jobs:

  snap:
    runs-on: ubuntu-latest

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        run: yarn dist:linux:snap
        
      - name: Upload
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.snap"
          draft: true
          verbose: true
  
  snap-armv7l:
    runs-on: ubuntu-latest

    steps:
      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1
        with:
          snapcraft_token: ${{ secrets.snapcraft_token }}

      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Build
        run: yarn --link-duplicates --pure-lockfile

      - name: Release
        if: contains(github.ref, 'develop')
        run: yarn dist:linux:snap:armv7l --publish always
